1559705105389	Sync.LogManager	DEBUG	Flushing file log
1559705105403	Sync.LogManager	DEBUG	Log cleanup threshold time: 1558841105403
1559705105426	Sync.LogManager	DEBUG	Done deleting files.
1559707012097	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559707012253	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559707012253	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559707012254	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559707012254	Sync.Service	INFO	Starting sync at 2019-06-05 05:56:52 in browser session DLDB2kz0MYXZ
1559707012254	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559707012264	Sync.Status	INFO	Resetting Status.
1559707012264	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559707012761	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559707013153	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559707013153	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559707013153	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559707013674	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559707013715	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559707014242	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559707014242	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559707014243	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559707014244	Sync.Service	INFO	Starting sync at 2019-06-05 05:56:54 in browser session DLDB2kz0MYXZ
1559707014247	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559707014247	Sync.Service	INFO	Cannot start sync: already syncing?
1559708924765	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559708925694	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559708925696	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559708927091	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559708933907	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections failed: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559708933907	Sync.Status	DEBUG	Status.sync: success.sync => error.login.reason.network
1559708933907	Sync.Status	DEBUG	Status.service: success.status_ok => error.sync.failed
1559708933907	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
1559708933908	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559708933911	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "The connection has timed out"  nsresult: "0x804b000e (NS_ERROR_NET_TIMEOUT)"  location: "<unknown>"  data: no] No traceback available
