1559632566013	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559634490094	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559634490258	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559634490258	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559634490259	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559634490259	Sync.Service	INFO	Starting sync at 2019-06-04 09:48:10 in browser session DLDB2kz0MYXZ
1559634490259	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559634490260	Sync.Status	INFO	Resetting Status.
1559634490260	Sync.Status	DEBUG	Status.service: success.status_ok => success.status_ok
1559634490757	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559634491221	Sync.SyncScheduler	DEBUG	Network link status changed to "down". Offline?: false
1559634491221	Sync.SyncScheduler	DEBUG	Clearing sync triggers and the global score.
1559634491221	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=schedule)
1559634491689	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559634492240	Sync.SyncScheduler	DEBUG	Network link status changed to "up". Offline?: false
1559634492240	Sync.SyncScheduler	DEBUG	Network link looks up. Syncing.
1559634492242	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559634492242	Sync.Service	INFO	Starting sync at 2019-06-04 09:48:12 in browser session DLDB2kz0MYXZ
1559634492248	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559634492248	Sync.Service	INFO	Cannot start sync: already syncing?
1559634493420	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559634494355	Sync.SyncScheduler	DEBUG	Woke from sleep.
1559634494355	Sync.SyncScheduler	DEBUG	Online, will sync in 2s.
1559634494355	Sync.SyncScheduler	DEBUG	Next sync in 2000 ms. (why=wake_notification)
1559634494356	Sync.SyncScheduler	DEBUG	Network link status changed to "changed". Offline?: false
1559634496558	Sync.Service	DEBUG	User-Agent: Firefox/67.0 (Intel Mac OS X 10.14) FxSync/1.69.0.20190516215225.desktop
1559634496558	FirefoxAccounts	INFO	Polling device commands.
1559634496558	Sync.Service	INFO	Starting sync at 2019-06-04 09:48:16 in browser session DLDB2kz0MYXZ
1559634496559	Sync.Service	DEBUG	Exception calling anonymous function: LockException: Could not acquire lock. Label: "service.js: sync".(resource://services-sync/util.js:41:5) JS Stack trace: LockException@util.js:41:5
throwLockException@util.js:115:11
WrappedLock@util.js:129:15
_lockedSync@service.js:1164:8
sync/<@service.js:1118:18
WrappedCatch@util.js:103:27
sync@service.js:1119:7
1559634496559	Sync.Service	INFO	Cannot start sync: already syncing?
1559634496560	Services.Common.RESTRequest	TRACE	local time, offset: 1559634496560, 386
1559634496561	Services.Common.RESTRequest	DEBUG	GET request to https://api.accounts.firefox.com/v1/account/device/commands?index=0
1559634496561	Services.Common.RESTRequest	TRACE	HTTP Header authorization: ***** (suppressed)
1559634496561	Services.Common.RESTRequest	TRACE	HTTP Header content-type: text/plain
1559634496562	Services.Common.RESTRequest	TRACE	HTTP Header accept-language: de,en-us,en
1559634499372	Sync.Resource	WARN	GET request to https://sync-535-us-west-2.sync.services.mozilla.com/1.5/80856074/info/collections?v=1.69.0 failed: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1559634499372	Sync.ErrorHandler	ERROR	Sync encountered an error: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
1559634499373	Sync.SyncScheduler	DEBUG	Next sync in 3600000 ms. (why=reschedule)
1559634499378	Sync.Service	DEBUG	Exception calling anonymous function: [Exception... "Abort"  nsresult: "0x80004004 (NS_ERROR_ABORT)"  location: "<unknown>"  data: no] No traceback available
